### PR TITLE
Fix security bug in presign protocol

### LINKED ISSUE #325: Fix issue with round two message validation in presign
Presign currently does not wait to receive all of the round one messages before processing the round two messages, which differs from the protocol specified in the paper. The goal of this issue is to fix that, and where applicable further align the implementation with the protocol description.

### PR DESCRIPTION
**Pull request by amaloz**
Closes #325.

This commit fixes a security bug in the presign protocol. In the protocol specification, each round requires that all messages from the prior round be received (and verified) before proceeding. Unfortunately, this is not what the code was doing, particular in round two of the protocol, where it would process a participant's message as soon as it was received.

This commit fixes that bug, alongside further aligning the presign implementation with keygen and auxinfo in terms of code structure.

This commit does NOT address any other issues related to a security audit.

### CODE REVIEW

File: src/presign/participant.rs [hunk 1]
```diff
@@ -329,69 +331,62 @@ impl PresignParticipant {
     fn gen_round_one_msgs<R: RngCore + CryptoRng>(
         &mut self,
         rng: &mut R,
-        message: &Message,
+        sid: Identifier,
```
Comment (amaloz) [inline src/presign/participant.rs:334]: Note: Changing `message` -> `sid` in these `gen_...` functions wasn't strictly necessary for this PR, however it did make the development process easier (as it helped me catch where message info was being used where it shouldn't have been). Given that this change will be reflected in the upcoming presign audit, I think it makes sense to keep it here.

File: src/presign/participant.rs [hunk 2]
```diff
@@ -329,69 +331,62 @@ impl PresignParticipant {
...
             rng,
             MessageType::Presign(PresignMessageType::RoundOneBroadcast),
             serialize!(&r1_public_broadcast)?,
-            message.id(),
+            sid,
             BroadcastTag::PresignR1Ciphertexts,
         )?;
-
-        // Additionally, handle any round 1 messages which may have been received too
-        // early
```
Comment (marsella) [inline src/presign/participant.rs:373]: I think we still need this check.

I'm concerned about the case where we have not completed `ready`, we get a r1 broadcast and regular message from another party. In that case we'd do the whole r1 for those messages -- there's no check in the `handle_round_one` message functions to see if we finished the ready round.

Ready stuff is slightly weird because it's not in the protocol description, but I think what happens in the code is that every party self-initializes, then sends a "ready" message to every other party, and we only start once we've gotten all of them. We might want to stop doing that, but I'd rather remove it in a separate PR.

File: src/presign/participant.rs [hunk 3]
```diff
@@ -422,21 +416,60 @@ impl PresignParticipant {
         message: &Message,
         input: &Input,
     ) -> Result<ProcessOutcome<<Self as ProtocolParticipant>::Output>> {
-        info!("Handling round one presign message.");
+        info!("Presign: Handling round one message.");
 
-        // Check if we have both have received the broadcasted ciphertexts that we need
-        // in order to respond and have started round one
-        if !(self
+        // First check that we have the round one public broadcast from this
```
Comment (marsella) [inline src/presign/participant.rs:421]: todo: following up other comment on "ready" messages, I think we also need a check that the ready round is complete.

File: src/presign/participant.rs [hunk 4]
```diff
@@ -452,89 +485,62 @@ impl PresignParticipant {
     /// response to the sender, without having to rely on any other round
     /// one messages from other participants aside from the sender.
```
Comment (marsella) [inline src/presign/participant.rs:486]: todo: I think this doc is now outdated.

File: src/presign/participant.rs (hunk 1 above)
Comment (marsella) [reply src/presign/participant.rs:334]: This is fine by me!

**Review by marsella — CHANGES_REQUESTED** [review]
Thanks for fixing this! I'm happy with the change to processing between round 1 and round 2.

I think you have made this closer to the paper, but the way we do "ready" messages is not canonical with the paper right now, so their handling is different here from the other protocols. I'm inclined to make the protocols match and reduce the # of ready messages later, but I'm open to arguments otherwise.

File: src/presign/participant.rs (hunk 2 above)
Comment (amaloz) [reply src/presign/participant.rs:373]: I think that's okay: we can handle round one messages before we ourselves have generated our round one message (which is really what `ready` seems to be all about: making sure all parties are ready before we generate messages to send).

This is also how the other protocols (`auxinfo` and `keygen`) work (not that that means it's correct, just that if this really is an issue here we'll need to address it in those protocols as well)

File: src/presign/participant.rs (hunk 3 above)
Comment (amaloz) [reply src/presign/participant.rs:421]: It actually looks like currently the "ready" messages aren't strictly necessary (and this applies to all the protocols): suppose we get r1 messages from all the parties. We then proceed to `gen_round_two_msgs`, which first checks whether we've generated our own r1 message. If not, we run `gen_round_one_msgs`. It appears this triggers regardless of what happens with the ready messages.

If I do add a check that `ready` has completed, the protocol hangs, which makes me wonder if `ready` messages haven't been really doing their job all along...

File: src/presign/participant.rs (hunk 2 above)
Comment (marsella) [reply src/presign/participant.rs:373]: Oh, I see, thanks for clarifying.

File: src/presign/participant.rs (hunk 3 above)
Comment (marsella) [reply src/presign/participant.rs:421]: Hm, that's interesting. I feel like ready messages are a bit of an attempt to solve a much bigger deployment problem (how do you synchronize initialization of all the parties so that no messages get lost?) that I'd rather offload onto the calling application. Anyway, we can leave it for now.
