### PR TITLE
Fix tiny bounds-sampling bugs and adjust sampling calls

### LINKED ISSUE #85: Double-check all the bounds in the util module
There are several methods in `util.rs` that draw elements from ranges. Make sure all these ranges are defined correctly. In particular, the paper says (please confirm):
- `+/- q` is inclusive of `+q`, `-q`
- `Z_N` is _not_ inclusive of `N`

### PR DESCRIPTION
**Pull request by marsella**
Closes #85 

This fixes a couple of little bugs around sampling. In one or two places, the ranges we sampled from weren't quite correct. A range used for testing only was not correct. And the general plus/minus range sampling was off by one.

I also made a couple of quality-of-life improvements, including adjusting the names of the sampling functions (open to alternate suggestions if you don't like these changes) and adding another convenience function for a common sampling format.

This review is kind of detail-oriented because there are so many little ranges. I would prefer a focus on making sure that the changes don't change anything in the code (beyond the bugs noted inline). Don't worry about comparing to the paper -- I did this as I went, but I think we can re-audit that as we do the code-quality checks on each ZKP.

### CODE REVIEW

File: src/utils.rs [hunk 1]
```diff
@@ -67,50 +67,60 @@ impl<'de> Deserialize<'de> for CurvePoint {
...
 ) -> crate::errors::Result<BigNumber> {
-    if min_bound >= n {
+    if min >= max {
         return bail!("min_bound needs to be less than n");
     }
-    let min_bound_bn = (BigNumber::one() << n) - (BigNumber::one() << min_bound);
-    let val = BigNumber::from_rng(&(min_bound_bn + (BigNumber::one() << min_bound)), rng);
+    // Sample from [0, 2^n - 2^min], then add 2^min to bump into correct range.
+    let min_bound_bn = (BigNumber::one() << max) - (BigNumber::one() << min);
+    let val = BigNumber::from_rng(&min_bound_bn, rng) + (BigNumber::one() << min);
```
Comment (marsella) [inline src/utils.rs:122]: note: This is just used for testing but I intentionally changed the range here. We need to sample from the correct-size range, then bump the value up into the correctly-bounded range.

File: src/zkp/pienc.rs [hunk 2]
```diff
@@ -89,11 +89,11 @@ impl Proof for PiEncProof {
...
     ) -> Result<Self> {
         // Sample alpha from +- 2^{ELL + EPSILON}
-        let alpha = random_bn_in_range(rng, ELL + EPSILON);
+        let alpha = random_plusminus_by_size(rng, ELL + EPSILON);
 
-        let mu = random_bn_in_range(rng, ELL) * &input.setup_params.N;
+        let mu = random_plusminus_scaled(rng, ELL, &input.setup_params.N);
         let r = random_bn_in_z_star(rng, &input.N0)?;
-        let gamma = random_bn_in_range(rng, ELL + EPSILON) * &input.setup_params.N;
+        let gamma = random_plusminus_scaled(rng, ELL + EPSILON, &input.setup_params.N);
```
Comment (marsella) [inline src/zkp/pienc.rs:96]: Note: These ranges are intentionally different. I think the original was a bug.

File: src/utils.rs [hunk 3]
```diff
@@ -67,50 +67,60 @@ impl<'de> Deserialize<'de> for CurvePoint {
...
+    max: usize,
+    min: usize,
 ) -> crate::errors::Result<BigNumber> {
-    if min_bound >= n {
+    if min >= max {
         return bail!("min_bound needs to be less than n");
     }
-    let min_bound_bn = (BigNumber::one() << n) - (BigNumber::one() << min_bound);
-    let val = BigNumber::from_rng(&(min_bound_bn + (BigNumber::one() << min_bound)), rng);
+    // Sample from [0, 2^n - 2^min], then add 2^min to bump into correct range.
```
Comment (amaloz) [inline src/utils.rs:120]: I think there's a typo in this comment, should it be `2^max - 2^min`?

**Review by amaloz — APPROVED** [review]
Looks good! Only one very minor comment.
