### PR TITLE
Fix Chinese remainder theorem bug

### LINKED ISSUE #24: test_chinese_remainder_theorem() has a small chance of failing
As shown in this CI run: https://github.com/boltlabs-inc/tss-ecdsa/actions/runs/3430896811/jobs/5718398191
The test should be modified to minimize the chance of interference with unrelated CI runs.

To close this issue, we should
- [ ] figure out what properties the CRT inputs need to satisfy
- [ ] In the happy test, validate them before calling the function.
- [ ] Add failure-case tests to make sure when those properties aren't satisfied, the CRT fails.

### PR DESCRIPTION
**Pull request by marsella**
Fix #24 

I'm pretty sure @tyurek already fixed this bug when he fixed the "two primes drawn from a list must be different" bug. To add confidence, I added some extra checks about coprimality in the happy test, and added two tests to look at specific failure cases based on the assumptions of the CRT.

Also improved docs on the CRT function and added another error.

### CODE REVIEW

File: src/errors.rs [hunk 1]
```diff
@@ -23,6 +23,8 @@ pub enum InternalError {
     NoSquareRoots,
     /// Elements are not coprime
     NotCoprime,
+    /// One or more of the integer inputs to the Chinese remainder theorem were outside the expected range.
+    InvalidIntegers,
```
Comment (marsella) [inline src/errors.rs:27]: question: I added this to our big old `InternalError`, but I could alternately take it and `NotCoprime` (and maybe others) and start a `PiModError` enum in that module. This is a little jumpstart on our existing error handling issues.

File: src/zkp/pimod.rs [hunk 2]
```diff
@@ -437,7 +450,17 @@ fn y_prime_combinations(
...
+        rngs::{OsRng, StdRng},
+        Rng, RngCore, SeedableRng,
+    };
+
+    fn rng() -> StdRng {
+        let mut seeder = OsRng;
+        let seed = seeder.gen();
+        eprintln!("seed: {:?}", seed);
+        StdRng::from_seed(seed)
+    }
```
Comment (marsella) [inline src/zkp/pimod.rs:463]: note: This will probably go away when we do #28 fully (e.g. it'll get centralized in `lib.rs` or someplace).

File: src/errors.rs (hunk 1 above)
Comment (gatoWololo) [reply src/errors.rs:27]: Good question. I will add some thoughts here about error handling. Tagging @indomitableSwan @tyurek for visibility!

Fundamentally, our error handling should be useful:
- It should be easy to use, this usually translates to just being able to use `?` and having it just work. Adding `From` trait implementations between types can help avoid `.map_error(...)`, etc. We shouldn't be constantly battling the `?` operator or too many error type conversions.
- It should provide useful information. This can be in the form of more granular variants for our error type, where the name carries enough meaning and is granular enough to differentiate it from other errors. We could also choose to have our error type carry data, e.g. `InvalidInteger` vs `InvalidInteger(BigNumber)` which would carry the offending number as part of its data.
- Error origination: When you have errors originating from several layers down the call stack, and getting propagated up it can be difficult to tell exactly where the error originated from. For lock-keeper, logging has largely made this a non-issue. I expect we can do the same here.

Other things to think about:
- Matching on variants: Will we (or an application using our library) ever need to match on the error variant type and branch control flow based on the result? If so, we should keep this in mind when designing our variants.

This may sound complicated, but in practice it shouldn't be too bad. Just wanted to list things to keep in mind. We also want to avoid over-engineering, e.g. what would be the issue with having one big enum with all our errors? I don't really see this causing issues.

**Review by tyurek — APPROVED** [review]
Additional tests look sane and thorough. Lots of error-handling overhaul here. I don't really have an informed opinion on that part (though I'm slightly sad to see the simplified Result enum go) so I'll defer to those with more experience. 

If this is the general method we're using for rewriting errors though, it might be good to through a pointer to this rewrite in the error handling epic or something

**Comment by marsella** [comment]
> Lots of error-handling overhaul here. I don't really have an informed opinion on that part (though I'm slightly sad to see the simplified Result enum go) so I'll defer to those with more experience.
> 
> If this is the general method we're using for rewriting errors though, it might be good to through a pointer to this rewrite in the error handling epic or something

I was excited about this approach but it is kind of uglier than I hoped for. @gatoWololo also had an initial preference for a single, nice error enum, so maybe we should stick with that.

File: src/errors.rs (hunk 1 above)
Comment (marsella) [reply src/errors.rs:33]: I tried separating out a `PiModError` but it failed on the first point, primarily. Ugly `Result` types and kind of funky returning. So, I decided to keep this and other `PiMod` exclusive errors here.
