### PR TITLE
fix sampling range for presigning elements

### LINKED ISSUE #123: Fix sampling range in presigning
In Presigning round 2, we draw `beta` and `beta_hat` from plus/minus `2^ell`. I think it should be `ell'` (that's `ELL_PRIME`). The protocol draws from fancy-J, which is defined in the Nota Bene on page 23.

- [ ] Double-check that this is actually a bug
- [ ] Fix it

### PR DESCRIPTION
**Pull request by marsella**
Closes #123 

I traced the usage of these two elements `beta` and `beta_hat` in presigning. I feel confident about the change to the range -- there was a complicated explanation of the intended range but it was all about specific numbers rather than our overall parameters and was talking about doing something tricky. I think that was outdated documentation, and I fixed the range to match the protocol description (and the eventual proof verification in both paper and implementation that those two elements are in the expected range).

I also noticed something weird happening with the sign of those values. The protocol calls for it to sometimes be negative, but the implementation makes them always positive. When I changed the implementation to match the paper, a proof failed. This is to be expected -- the PiAffg proof matches the paper, but only works when the sign of `beta` is positive in every encryption. I added some documentation about this discrepancy; happily, I don't think it affects the security of the proof.

Reviewer request: 
- Verify that the docs make sense
- Optional: do the same dive into the proof that I did to add confidence to my claim that it's not a security-critical change.

### CODE REVIEW

File: src/presign/participant.rs [hunk 1]
```diff
@@ -977,12 +975,18 @@ impl PresignKeyShareAndInfo {
...
-        // Picking betas as elements of [+- 2^384] here is like sampling them from the
-        // distribution [1, 2^256], which is akin to 2^{ell + epsilon} where ell
-        // = epsilon = 384. Note that we need q/2^epsilon to be negligible.
-        let beta = random_plusminus_by_size(rng, ELL);
-        let beta_hat = random_plusminus_by_size(rng, ELL);
-
+        let beta = random_plusminus_by_size(rng, ELL_PRIME);
+        let beta_hat = random_plusminus_by_size(rng, ELL_PRIME);
+
+        // Note: The implementation specifies that we should encrypt the negative betas here, and
```
Comment (Ra1issa) [inline src/presign/participant.rs:981]: Suggestion: I'd recommend that you cite the relevant sections in the paper in this discussion just for documentation's sake.

File: src/presign/participant.rs [hunk 2]
```diff
@@ -977,12 +975,18 @@ impl PresignKeyShareAndInfo {
         sender_r1_priv: &RoundOnePrivate,
         receiver_r1_pub_broadcast: &RoundOnePublicBroadcast,
     ) -> Result<(RoundTwoPrivate, RoundTwoPublic)> {
-        // Picking betas as elements of [+- 2^384] here is like sampling them from the
-        // distribution [1, 2^256], which is akin to 2^{ell + epsilon} where ell
-        // = epsilon = 384. Note that we need q/2^epsilon to be negligible.
-        let beta = random_plusminus_by_size(rng, ELL);
-        let beta_hat = random_plusminus_by_size(rng, ELL);
-
+        let beta = random_plusminus_by_size(rng, ELL_PRIME);
```
Comment (Ra1issa) [inline src/presign/participant.rs:978]: Suggestion: I'd suggested changing the name of the method to `sample_random_from_plusminus_by_size`, or something that highlight what `random` refers to.

**Comment by Ra1issa** [comment]
@marsella my reviews are up and ready.

File: src/presign/participant.rs (hunk 2 above)
Comment (marsella) [reply src/presign/participant.rs:978]: I'm going to punt this to #145 because this will touch a bunch of code unrelated to this PR. I would love to be able to call this with `sample::random_plusminus_by_size()` so there's a verb involved.

File: src/presign/participant.rs (hunk 1 above)
Comment (marsella) [reply src/presign/participant.rs]: Ooh yes. Fixed!

**Review by Ra1issa — APPROVED** [review]
