### PR TITLE
Fix key-size bug

### LINKED ISSUE #56: Ensure n-bit Paillier modulus is generated
Right now we pick two (n/2)-bit primes to create a Paillier modulus, but we do not guarantee that the product of these two primes will be n-bits. Typically this is done by picking your primes with the topmost two bits set to 1.

### PR DESCRIPTION
**Pull request by marsella**
Fixes #56 

This PR ballooned a little bit. In #60, I made an API for key generation that takes primes as parameters. However, I realized here that 
1. we never create a new Paillier key from primes that we didn't just generate, and
2. we never generate primes that aren't used in Paillier keys (outside of tests).

So, I decided to move all the prime generation methods into a mini-module within the Paillier module, and to update the key generation API to just take an RNG and generate the primes internally. It now also returns the prime factors, since they're not directly retrievable from the decryption key but we need them in subsequent operations.

The prime generation module didn't change functionally; I cleaned up some documentation and consolidated function calls a little bit.

The prime generation steps only change in order to address the actual issue I was trying to solve: adding size checks to the primes we generate and the modulus that results. I also built in a retry mechanism that adds some complexity, but I hopefully added enough inline documentation that it's understandable.

Specific reviewer requests:
- @gatoWololo : I will put one or two Rust questions inline
- @tyurek : Are there any additional properties of the primes used for Paillier moduli that you think I missed? 

Design thoughts
- Maybe the prime factors generated for a `PaillierDecryptionKey` should be in their own wrapper type, like `PaillierFactor`. It might be useful to distinguish them from arbitrary big numbers in the proofs, and then we could tag them with `zeroize` because they're very sensitive data.
- A very common pattern in tests is to generate a Paillier decryption key, derive the encryption key, and then use the factors from decryption to compute `N = p * q`. `N` is a public part of the encryption key, though. I think this will go away when we encode the proofs with Paillier types instead of `BigNumber`s. If not, we should think about making an explicit method on the encryption key to retrieve `N` and `N^2` to remove some of that extra multiplication.

### CODE REVIEW

File: src/paillier.rs [hunk 1]
```diff
@@ -61,15 +63,58 @@ impl PaillierDecryptionKey {
...
+
+        // A Paillier decryption key is the product of the two primes, but sometimes two n/2-bit primes can produce an
+        // n-1 bit modulus. Allow some retries to handle that error.
+        let (p, q) = std::iter::repeat_with(generate_prime_pair)
+            .take(CRYPTOGRAPHIC_RETRY_MAX)
+            .find(|result| result.is_some())
+            // We hit the maximum number of retries without getting an acceptable pair.
+            .ok_or(InternalError::RetryFailed)?
+            // The `find` function failed to actually give us `Some`.
+            .ok_or(InternalError::InternalInvariantFailed)?;
```
Comment (marsella) [inline src/paillier.rs:100]: Rust question: I want this to evaluate lazily so it only generates prime pairs until we get one that works. The `take` won't execute all 500 elements, right?

File: src/paillier.rs [hunk 2]
```diff
@@ -78,3 +123,116 @@ impl PaillierDecryptionKey {
...
+    lazy_static::lazy_static! {
+        static ref POOL_OF_PRIMES: Vec<BigNumber> = get_safe_primes_from_file();
+    }
+
+    #[cfg(test)]
+    fn get_safe_primes_from_file() -> Vec<BigNumber> {
+        crate::safe_primes_512::SAFE_PRIMES
+            .iter()
+            .map(|s| BigNumber::from_slice(hex::decode(s).unwrap()))
+            .filter(|prime| prime.bit_length() == PRIME_BITS)
```
Comment (marsella) [inline src/paillier.rs:155]: note: I added this `filter`. Some of the primes in the list are not exactly 512 bits.

File: src/paillier.rs [hunk 3]
```diff
@@ -78,3 +123,116 @@ impl PaillierDecryptionKey {
...
+    use crate::parameters::PRIME_BITS;
+
+    use super::{prime_gen, PaillierDecryptionKey};
+
+    fn rng() -> StdRng {
+        let mut seeder = OsRng;
+        let seed = seeder.gen();
+        eprintln!("seed: {:?}", seed);
+        StdRng::from_seed(seed)
+    }
```
Comment (marsella) [inline src/paillier.rs:198]: note: I would expect this function will get pulled out of this module since we'll want it for every test, eventually. But I leave that to #28.

File: src/paillier.rs [hunk 4]
```diff
@@ -78,3 +123,116 @@ impl PaillierDecryptionKey {
...
+        assert_eq!(p.bit_length(), PRIME_BITS);
+        assert_eq!(q.bit_length(), PRIME_BITS);
+
+        let modulus = &p * &q;
+        assert_eq!(decryption_key.0.n(), &modulus);
+        assert_eq!(modulus.bit_length(), 2 * PRIME_BITS);
+    }
+
+    #[test]
+    #[ignore = "slow"]
```
Comment (marsella) [inline src/paillier.rs:232]: note: This never gets run right now, but once we address #65 it should be run sometimes.

File: src/paillier.rs [hunk 5]
```diff
@@ -61,15 +63,58 @@ impl PaillierDecryptionKey {
...
-    pub(crate) fn from_primes(p: &BigNumber, q: &BigNumber) -> Result<Self> {
-        Ok(PaillierDecryptionKey(
-            libpaillier::DecryptionKey::with_primes(p, q)
+    /// The factors `p` and `q` are `PRIME_BITS`-long safe primes, and the resulting
+    /// modulus is `2 * PRIME_BITS` long.
+    pub(crate) fn new(
+        rng: &mut (impl CryptoRng + RngCore),
+    ) -> Result<(Self, BigNumber, BigNumber)> {
+        // Local utility function to generate prime pairs and check their resulting modulus length.
+        let generate_prime_pair = || {
```
Comment (gatoWololo) [inline src/paillier.rs:74]: I'm a fan of local functions! I think this one is big enough to be a named local function. This way we can give it a signature:
```diff
- let generate_prime_pair = || {
+ fn generate_prime_pair() -> Option<(BigNumber, BigNumber)> {
```

File: src/paillier.rs (hunk 1 above)
Comment (gatoWololo) [reply src/paillier.rs:100]: I had to test it out with an example. Just from reading the doc, I thought it would always execute `CRYPTOGRAPHIC_RETRY_MAX` number of times. But yes, it is lazy!

File: src/paillier.rs (hunk 2 above)
Comment (gatoWololo) [reply src/paillier.rs:155]: Right, I saw the slack convo. Can you add a comment explaining the filter to the code?

**Review by gatoWololo — APPROVED** [review]
Looks good! I enjoy a good refactor :relaxed:

File: src/paillier.rs (hunk 5 above)
Comment (marsella) [reply src/paillier.rs:74]: I like that idea but the signature is kind of ugly because this actually needs to take an `rng`. Does this change your preference? I ended up with
```rust
    fn generate_prime_pair(
        rng: &mut (impl CryptoRng + RngCore),
    ) -> impl FnMut() -> Option<(BigNumber, BigNumber)> + '_ { ... }
```

Comment (gatoWololo) [reply src/paillier.rs]: Oh yeah, that's way uglier :mask: . We should just keep the original code! I forgot about the `rng` being captured by the closure. NVM!
