### PR TITLE
Thread output-return throughout auxinfo

### LINKED ISSUE #193: Fix auxinfo output type and correctness
#179 introduces a new `Output` type to a `ProtocolParticipant` that defines the output it's expected to produce. However, in order to keep that PR to a reasonable size, the aux-info protocol is incorrect / incomplete in two ways:

1. It doesn't correctly define the output type. Since the protocol implementation currently loads outputs into `main_storage` instead of returning them, the output type of the protocol is set to `()`. Instead, it should include public and private aux info outputs.
2. It doesn't indicate correctly when the protocol is done. The protocol implementation currently only produces messages at each stage. Instead, the `handle_round_X_msgs` functions should return the output when it's available.

In order to avoid breaking other protocols that expect the output of auxinfo to be in `Storage`, it's okay to leave the code that loads the outputs into `main_storage`. That will be extracted in a separate issue #180.

## Completion criteria
- [x] Define the auxinfo output type correctly (it should include the values loaded into main storage at the end of the protocol)
- [x] Update the message handling methods to return the output when it's available, and `None` when it's not available
- [x] Add checks to tests that we get output in situations where we expect it

### PR DESCRIPTION
**Pull request by marsella**
Closes #193 

I let this PR expand out of reasonable scope; I apologize to the reviewers.

Primary changes are:
- Updates the auxinfo protocol to return public and private key material
    - Adds a participant ID field to public key material to indicate who it belongs to
    - Adds conditions to aux info tests to make sure the outputs are as expected
- Improves code quality of `AuxInfo{Commit, Decommit, Public, Private, Witness}`, including limiting visibility of parameters to add confidence that they're well-formed, adding validation at construction and deserialization, zeroizing secrets, and adding custom debug implementations to some maybe-secret types.
- Moves some existing functionality (`process_ready_message`) into `ProtocolParticipant` 
- Adds a new method to combine `ProcessOutcome`s in a logical way.

### CODE REVIEW

File: src/auxinfo/participant.rs [hunk 1]
```diff
@@ -42,10 +41,9 @@ pub(crate) struct AuxInfoParticipant {
 }
 
 impl ProtocolParticipant for AuxInfoParticipant {
-    // Currently, AuxInfo puts output directly into persistent storage instead of
-    // returning it to the calling Participant.
-    // TODO #193: Update this type to actually define the output.
-    type Output = ();
+    // The output type includes `AuxInfoPublic` material for all participants
+    // (including ourselves) and `AuxInfoPrivate` for ourselves.
+    type Output = (Vec<AuxInfoPublic>, AuxInfoPrivate);
```
Comment (marsella) [inline src/auxinfo/participant.rs:46]: question: Should we attach a session ID to these `Output`s, or is that the responsibility of the calling application? There's misuse potential if the caller doesn't carefully bind outputs to the session from whence they came, and ends up reusing them in incorrect contexts, but I'm not sure how well we can handle that from within.

File: src/presign/participant.rs [hunk 2]
```diff
@@ -1145,8 +1145,14 @@ impl PresignKeyShareAndInfo {
...
-            let alpha = self.aux_info_private.sk.decrypt(&r2_pub_j.D)?;
-            let alpha_hat = self.aux_info_private.sk.decrypt(&r2_pub_j.D_hat)?;
+            let alpha = self
+                .aux_info_private
+                .decryption_key()
+                .decrypt(&r2_pub_j.D)?;
+            let alpha_hat = self
+                .aux_info_private
+                .decryption_key()
+                .decrypt(&r2_pub_j.D_hat)?;
```
Comment (marsella) [inline src/presign/participant.rs:1155]: note: this just changes direct access to `sk` to controlled call to `decryption_key()`

File: src/auxinfo/auxinfo_commit.rs [hunk 3]
```diff
@@ -32,43 +35,100 @@ impl AuxInfoCommit {
...
+        auxinfo_decommit.public_keys.verify()?;
+
+        // Owner must be consistent across message, public keys, and decommit
+        if *auxinfo_decommit.public_keys.participant() != auxinfo_decommit.sender {
+            error!(
+                "Deserialized AuxInfoDecommit has different participant IDs in the sender ({}) and public_keys ({}) fields",
+                auxinfo_decommit.sender,
+                auxinfo_decommit.public_keys.participant(),
+            );
+            return Err(InternalError::Serialization);
```
Comment (gatoWololo) [inline src/auxinfo/auxinfo_commit.rs:102]: I don't know if this is necessarily a `Serialization` error. Instead, it should be an `InternalInvariantFailed` error? In my mind `Serialization` errors are only for when bytes fail to deserialize into some expected type.

File: src/auxinfo/participant.rs [hunk 4]
```diff
@@ -83,30 +85,34 @@ impl ProtocolParticipant for AuxInfoParticipant {
...
-        let messages = match message.message_type() {
+        match message.message_type() {
             MessageType::Auxinfo(AuxinfoMessageType::R1CommitHash) => {
-                let (broadcast_option, mut messages) = self.handle_broadcast(rng, message)?;
+                let (broadcast_option, messages) = self.handle_broadcast(rng, message)?;
+
+                // This is kind of a bastardization of the outcome type, but this is basically a
+                // conversion from the broadcast outcome type (with a
+                // BroadcastOutput) to the aux-info outcome type (with a ()).
+                let broadcast_outcome = ProcessOutcome::from(None, messages);
```
Comment (gatoWololo) [inline src/auxinfo/participant.rs:95]: Come back to this, Omar

File: src/auxinfo/participant.rs [hunk 5]
```diff
@@ -225,24 +228,29 @@ impl AuxInfoParticipant {
             message.id(),
             &self.other_participant_ids.clone(),
         )?;
-        let mut messages = vec![];
 
         if r1_done {
```
Comment (gatoWololo) [inline src/auxinfo/participant.rs:232]: (I know you are just refactoring the code so this isn't against you). I hate this code. So weird that we call `handle_round_two_msg` from within `handle_round_one_msg` and return the results in a variable called "round_one_outcome" 😷😷😷

File: src/auxinfo/participant.rs [hunk 6]
```diff
@@ -593,35 +624,42 @@ mod tests {
         Ok(true)
     }
 
+    /// Pick a random participant and process one of the messages in their
+    /// inbox.
+    ///
+    /// Returns None if there are no messages for the selected participant.
+    #[allow(clippy::type_complexity)]
```
Comment (gatoWololo) [inline src/auxinfo/participant.rs:631]: lmao

File: src/auxinfo/participant.rs [hunk 7]
```diff
@@ -593,35 +624,42 @@ mod tests {
...
     fn process_messages<R: RngCore + CryptoRng>(
```
Comment (gatoWololo) [inline src/auxinfo/participant.rs:632]: Add `#[cfg(test)]` to this function

File: src/auxinfo/participant.rs [hunk 8]
```diff
@@ -637,14 +675,18 @@ mod tests {
...
         let mut rng = crate::utils::get_test_rng();
-        let mut quorum = AuxInfoParticipant::new_quorum(3, &mut rng)?;
+        let mut quorum = AuxInfoParticipant::new_quorum(QUORUM_SIZE, &mut rng)?;
         let mut inboxes = HashMap::new();
         let mut main_storages: Vec<Storage> = vec![];
         for participant in &quorum {
             let _ = inboxes.insert(participant.id, vec![]);
             main_storages.append(&mut vec![Storage::new()]);
         }
+        let mut outputs = std::iter::repeat_with(|| None)
```
Comment (gatoWololo) [inline src/auxinfo/participant.rs:687]: This is fancy :fire-emoji:

File: Cargo.toml [hunk 9]
```diff
@@ -32,6 +32,7 @@ serde = "1"
 sha2 = "0.9"
 thiserror = "1"
 tracing = "0.1.37"
+zeroize = "1"
```
Comment (gatoWololo) [inline Cargo.toml:35]: We specify this dependency with a minor version as well.

File: src/auxinfo/participant.rs [hunk 10]
```diff
@@ -83,30 +85,34 @@ impl ProtocolParticipant for AuxInfoParticipant {
...
-                let (broadcast_option, mut messages) = self.handle_broadcast(rng, message)?;
+                let (broadcast_option, messages) = self.handle_broadcast(rng, message)?;
+
+                // This is kind of a bastardization of the outcome type, but this is basically a
+                // conversion from the broadcast outcome type (with a
+                // BroadcastOutput) to the aux-info outcome type (with a ()).
+                let broadcast_outcome = ProcessOutcome::from(None, messages);
+
+                // If the round one broadcast worked, process the round one message.
                 if let Some(bmsg) = broadcast_option {
```
Comment (gatoWololo) [inline src/auxinfo/participant.rs:98]: I think I prefer a match statement when working with both variants of an `Option` like this.

File: src/participant.rs [hunk 11]
```diff
@@ -45,7 +46,22 @@ pub(crate) enum ProcessOutcome<O> {
...
+            ProcessOutcome::Terminated(_) => "Terminated",
+            ProcessOutcome::TerminatedForThisParticipant(_, _) => "Terminated for this participant",
+        };
+        write!(f, "ProcessOutcome::{descriptor}")
+    }
+}
+
+impl<O> ProcessOutcome<O>
+where
+    O: std::fmt::Debug,
```
Comment (gatoWololo) [inline src/participant.rs:63]: Probably doesn't matter, but this trait bound sticks out to me `O: std::fmt::Debug`. Why is it necessary?

Comment (gatoWololo) [reply src/participant.rs:63]: Oh NVM. I see how it is used for error logging.

File: src/participant.rs [hunk 12]
```diff
@@ -110,6 +155,56 @@ pub(crate) trait ProtocolParticipant {
         main_storage: &mut Storage,
     ) -> Result<ProcessOutcome<Self::Output>>;
 
+    /// Returns a list of all participant IDs, including `self`'s.
+    fn all_participants(&self) -> Vec<ParticipantIdentifier> {
+        std::iter::once(&self.id())
```
Comment (gatoWololo) [inline src/participant.rs:160]: How do you feel about this code that doesn't use iterators:
```rust
    let mut participant = self.other_ids().clone();
        participant.push(self.id());
        participant
```

File: src/auxinfo/participant.rs (hunk 7 above)
Comment (marsella) [reply src/auxinfo/participant.rs:632]: It's in `mod tests`!

File: src/auxinfo/participant.rs (hunk 8 above)
Comment (marsella) [reply src/auxinfo/participant.rs:687]: I really like initializing vectors like this, although I actually tried `vec![None; QUORUM_SIZE]` and it wouldn't let me because the `Some` type isn't `Clone` :|

File: src/auxinfo/info.rs [hunk 13]
```diff
@@ -6,39 +6,97 @@
...
+    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
+        f.debug_struct("AuxInfoPrivate")
+            .field("decryption key", &"[redacted]")
+            .finish()
+    }
 }
 
 /// The public Auxilary Information corresponding to a given Participant.
-#[derive(Serialize, Deserialize, Clone)]
+#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
```
[the remark this answers is not in the document]
Comment (marsella) [reply src/auxinfo/info.rs:54]: The parameters are all IDs and public keys so it should be fine to log. Thanks for checking!

[the remark this answers is not in the document]
Comment (marsella) [reply src/auxinfo/info.rs:54]: Although honestly we might want to not log them because it's going to make the logs impossible to read. All these key types are massive. Maybe we should make a long-term issue to log these things in some condensed or hashed format.

File: src/participant.rs (hunk 11 above)
Comment (marsella) [reply src/participant.rs:63]: I agree that it's kind of awkward.

File: src/participant.rs (hunk 12 above)
Comment (marsella) [reply src/participant.rs:160]: I feel positive! I was prematurely optimizing to avoid reallocating in case the cloned capacity is exactly the length and we have to reallocate, but in retrospect, it's not worth the readability hit.

File: src/participant.rs [hunk 14]
```diff
@@ -110,6 +155,56 @@ pub(crate) trait ProtocolParticipant {
...
+    }
+
+    /// Process a `ready` message: tell other participants that we're ready and
+    /// see if all others have also reported that they are ready.
+    fn process_ready_message<T: Storable>(
+        &mut self,
+        message: &Message,
+        storable_type: T,
+    ) -> Result<(ProcessOutcome<Self::Output>, bool)> {
+        self.storage_mut()
```
Comment (gatoWololo) [inline src/participant.rs:172]: Could you add a comment to this line. It is unclear to me why it is needed

File: src/participant.rs [hunk 15]
```diff
@@ -78,6 +94,34 @@ impl<O> ProcessOutcome<O> {
...
+
+    /// Consolidate a set of `ProcessOutcome`s, including `self`, into a single
+    /// outcome.
+    ///
+    /// This collects all of the messages into a single set, and makes sure that
+    /// there's no more than one output specified among all the outcomes.
+    pub(crate) fn consolidate(self, outcomes: Vec<Self>) -> Result<Self> {
+        let (outputs, messages): (Vec<_>, Vec<_>) = std::iter::once(self)
+            .chain(outcomes)
+            .map(|outcome| outcome.into_parts())
```
Comment (gatoWololo) [inline src/participant.rs:106]: This could just be `.map(Self::into_parts)`

File: src/auxinfo/auxinfo_commit.rs (hunk 3 above)
Comment (gatoWololo) [reply src/auxinfo/auxinfo_commit.rs]: Gotcha. Yeah `ProtcolError` sounds right.

File: src/auxinfo/participant.rs (hunk 8 above)
Comment (gatoWololo) [reply src/auxinfo/participant.rs:689]: :headstone:

**Review by gatoWololo — CHANGES_REQUESTED** [review]
Looks good. Overall, some minor comments.

File: Cargo.toml (hunk 9 above)
Comment (marsella) [reply Cargo.toml]: Done. Is this to avoid automatic upgrades to a breaking version?

File: src/auxinfo/participant.rs (hunk 1 above)
Comment (marsella) [reply src/auxinfo/participant.rs:60]: I'm going to stick with leaving it up to the calling application for now. Once we make progress on the public API, we can always add the session ID later.

File: Cargo.toml (hunk 9 above)
Comment (gatoWololo) [reply Cargo.toml]: Yes, since minor version bumps on behalf of the library could break our compilation in the future.

File: src/auxinfo/info.rs (hunk 13 above)
[the remark this answers is not in the document]
Comment (gatoWololo) [reply src/auxinfo/info.rs:54]: Haha. Is there any good reason for the `Debug` implementation to  print out the entire key types?

**Review by gatoWololo — APPROVED** [review]

File: src/auxinfo/info.rs (hunk 13 above)
[the remark this answers is not in the document]
Comment (marsella) [reply src/auxinfo/info.rs:54]: Eh, it seems useful to have some way to distinguish between different keys in the logs, but that could be done without the entire key. If we're getting truly weird cryptographic behavior it might be useful to know but I don't really expect that to be the primary kind of errors we're debugging with logs.
