### PR TITLE
453 code quality nits PiSch

### LINKED ISSUE #453: Address code quality nits in PiSch
On taking a final pass in #443, we identified the following remaining issues in the PiSch proof:

- [x] `commitment` field in `PiSchProof` doesn't need to be `pub(crate)`
- [x] `CommonInput` field name needs to be Rust-canonical, not a capital `X`.
- [x] `CommonInput::new` can put the `where` clause inline and remove the type parameter (`param: &'a impl AsRef<CurvePoint>`)
- [x] `ProverSecret` field name could use a more descriptive rename
- [x] L149 - use `CurvePoint` method instead of constructing it manually and calling `bn_to_scalar`
- [x] L153 error log should contain something descriptive about what actually failed
- [x] The `from_message` method should have validation of the `challenge` and `response` fields (both must be in the range `[0, k256_order)`, yes. 
- [x] The `from_message` method should not use the name `keygen_decommit` for a proof
- [x] The `fill_transcript` parameter name `A` is non-canonical; it should match the name of whatever is passed to it
- [x] Won't look at proofs carefully now because #115 is in progress, but there's a capital `X` in `with_random_schnorr_proof`. IT can be renamed to whatever the common input field name gets changed to.

### PR DESCRIPTION
**Pull request by hridambasu**
Closes #453

### CODE REVIEW

File: src/utils.rs [hunk 1]
```diff
@@ -47,6 +47,11 @@ impl CurvePoint {
     /// key
     pub const IDENTITY: Self = CurvePoint(k256::ProjectivePoint::IDENTITY);
 
+    /// Add a curvepoint to `self`.
+    pub(crate) fn add(&self, other: &CurvePoint) -> CurvePoint {
+        CurvePoint(self.0 + other.0)
+    }
+
```
Comment (marsella) [inline src/utils.rs:54]: todo: We actually implement `std::ops::Add` a bit below this; you should be able to use the `+` operator directly to add together `CurvePoint`s!

File: src/zkp/pisch.rs [hunk 2]
```diff
@@ -145,12 +146,16 @@ impl Proof2 for PiSchProof {
 
         let response_matches_commitment = {
             let lhs = CurvePoint::GENERATOR.multiply_by_scalar(&self.response)?;
-            let rhs =
-                CurvePoint(self.commitment.0 + input.X.0 * utils::bn_to_scalar(&self.challenge)?);
+            /*let rhs = CurvePoint(
+                self.commitment.0 + input.x_commitment.0 * utils::bn_to_scalar(&self.challenge)?,
+            );*/
```
Comment (marsella) [inline src/zkp/pisch.rs:151]: todo: remove commented-out code

File: src/zkp/pisch.rs [hunk 3]
```diff
@@ -200,18 +205,20 @@ impl PiSchProof {
     }
     pub(crate) fn from_message(message: &Message) -> Result<Self> {
         message.check_type(MessageType::Keygen(KeygenMessageType::R3Proof))?;
-        let keygen_decommit: PiSchProof = deserialize!(&message.unverified_bytes)?;
-        Ok(keygen_decommit)
+        let pischproofbytes: PiSchProof = deserialize!(&message.unverified_bytes)?;
+        assert!(pischproofbytes.challenge < k256_order());
+        //assert!(pischproofbytes.response < k256_order());
```
Comment (marsella) [inline src/zkp/pisch.rs:210]: todo: this will panic if it fails! Use a conditional and return an error (probably `ProtocolError`) instead.

also, question: why is the response check commented out?

File: src/zkp/pisch.rs [hunk 4]
```diff
@@ -200,18 +205,20 @@ impl PiSchProof {
...
         transcript: &mut Transcript,
         context: &impl ProofContext,
         input: &CommonInput,
-        A: &CurvePoint,
+        commitment: &CurvePoint,
     ) -> Result<()> {
         transcript.append_message(b"PiSch ProofContext", &context.as_bytes()?);
         transcript.append_message(b"PiSch CommonInput", &serialize!(&input)?);
-        transcript.append_message(b"A", &serialize!(A)?);
+        transcript.append_message(b"A", &serialize!(commitment)?);
```
Comment (marsella) [inline src/zkp/pisch.rs:221]: nit: change the context string `"A"` as well.

File: src/zkp/pisch.rs [hunk 5]
```diff
@@ -200,18 +205,20 @@ impl PiSchProof {
     }
     pub(crate) fn from_message(message: &Message) -> Result<Self> {
         message.check_type(MessageType::Keygen(KeygenMessageType::R3Proof))?;
-        let keygen_decommit: PiSchProof = deserialize!(&message.unverified_bytes)?;
-        Ok(keygen_decommit)
+        let pischproofbytes: PiSchProof = deserialize!(&message.unverified_bytes)?;
```
Comment (marsella) [inline src/zkp/pisch.rs:208]: minor name quibble: if you keep this name, it should be snake case, like `pisch_proof_bytes`. I would actually remove the `_bytes` modifier, though, since the type of this variable is a full-on `PiSchProof`, not just the bytes that can become a proof.

**Review by marsella — CHANGES_REQUESTED** [review]
Thanks, this looks good! Just a a few small changes.

File: src/zkp/pisch.rs (hunk 3 above)
Comment (marsella) [reply src/zkp/pisch.rs]: Aha. Looking at how we generate this, I think the idea you brought up in the team meeting is correct -- when we compute `response`, we use normal addition and multiplication instead of the modular +/* with `BigNumber`s. So it makes sense that it's too big. This is a bug; the paper explicitly says to calculate it `mod q`.

Do you want to change it here or in a separate issue? It should just be one line change  in `prove_from_precommit` to use `modadd` and `modmul` instead of `+` and `*`.

Comment (hridambasu) [reply src/zkp/pisch.rs]: changed in this PR itself.

**Review by marsella — APPROVED** [review]
Nice, easier fix than expected!
