### PR TITLE
465 Fix Negative tests in PiFac

### LINKED ISSUE #465: Fix "negative tests" in pifac
The `pifac` module includes lots of tests, but some of them are not testing exactly what they say they are testing. We need to review these and fix documentation / test names for the ones that are misleading.

Specifically, the test `test_no_small_factors_proof_negative_cases()` has many test of the following form:
```rust
// for a given valid `input` and `proof`:
let invalid_proof = PiFacProof::prove(input, ... other bad fields ...)?;
let invalid_input = CommonInput::new(...bad things...);
assert!(invalid_proof.verify(invalid_input, &(), &mut transcript()).is_err());
```
This applies to `small_proof`, and the two `mixed_proof`s.

However, these tests are failing because the common input is different between proving (`input`) and verifying (`invalid_input`), so the challenge will be wrong. It's a bit hard to tell because this proof, unlike the others, doesn't specifically include the challenge in the proof, so it's not explicit in the logs. If you print out the challenge in proving and verifying, though, you'll see it's different.

However, the proofs are trying to demonstrate different properties:
- `small_proof` manually selects small factors and expects to fail because the factors are not in the correct range. 
- `mixed proof`s choose a small and a normal-sized factor and expects to fail because one of the factors is too small

In fact, I think these test won't ever work because the proof actually tests that no factors are too large (e.g. the range check is an upper bound, not a lower bound). It doesn't explicitly encode that the modulus is supposed to be 2048 bits. See `test_modulus_cannot_have_large_factors` for the thing we can actually verify.

So, action items that remain are
- [x] Test my theory: fix the common input to be the same in the three identified tests and see if they fail
- [x] Look at the paper and see if we should add a "minimum size check" for `N` in validation, or if it's okay to assume that's checked outside the proof (see also: #466)
- [x] Either fix the tests or remove them.

### PR DESCRIPTION
**Pull request by hridambasu**
Closes #465

### CODE REVIEW

File: src/zkp/pifac.rs [hunk 1]
```diff
@@ -454,13 +451,9 @@ mod tests {
                 &mut rng2,
             )?;
 
-            assert!(small_proof
-                .verify(small_input, &(), &mut transcript())
-                .is_err());
+            assert!(small_proof.verify(input, &(), &mut transcript()).is_err());
```
Comment (marsella) [inline src/zkp/pifac.rs:454]: Now this is testing the same thing as the previous test (`incorrect_factors`): the (small) secret inputs are not the factors of the modulus in `input`.

Do you think there's value in testing inputs =/= modulus in two ways? If so, you can keep it but the documentation on L443 needs to change to describe the two ways in which this test fails (the factors do not correspond to the modulus and the factors are small).

File: src/zkp/pifac.rs [hunk 2]
```diff
@@ -469,13 +462,9 @@ mod tests {
                 &mut rng2,
             )?;
 
-            assert!(mixed_proof
-                .verify(mixed_input, &(), &mut transcript())
-                .is_err());
+            assert!(mixed_proof.verify(input, &(), &mut transcript()).is_err());
```
Comment (marsella) [inline src/zkp/pifac.rs:465]: Again, there are two failure modes here: the factors don't match the modulus, and one of them is too small. At the very least the documentation needs to explain this.

File: src/zkp/pifac.rs [hunk 3]
```diff
@@ -484,9 +473,7 @@ mod tests {
...
```
Comment (marsella) [inline src/zkp/pifac.rs:476]: Likewise.

**Review by marsella — CHANGES_REQUESTED** [review]
With these changes, all 4 of the tests in this method check that when the secret-input factors are not actually the factors of the modulus, the test fails. I think that needs to be made way more explicit in the documentation. We might also change the name of the overall test to be clear that it's all about factors not matching modulus.

What did you find about validating the modulus size in the proof verification? I think we need to consider the assumption written at the bottom of Fig 28: 
> The proof guarantees that each `p, q > 2^l` (assuming `2^(2l+ε) ≈ √N_0`)

I don't think we check that property of `N_0`.

**Review by marsella — APPROVED** [review]
Thanks for fixing. I'll make an issue about modulus size validation.
