### PR TITLE
Fix error handling when drawing random ZStar

### LINKED ISSUE #41: Fix error handling for random z-star generation
Right now the `random_bn_in_z_star` method (in `util.rs`) can return 0 in a rare case. This is statistically improbable, but it is still better to use standard error handling rather than to return an invalid value and require callers to manually check it.

To close this issue:
- [x] Update method to return a `Result`

This might be better to do after #58 is complete, because we'll have some error enums set up.

### PR DESCRIPTION
**Pull request by marsella**
Fix #41 

This adds error handling and, uh, correctness to drawing elements from `ZStar` (not a real type yet). 

Future design thought: The coprimality test we have now works for any modulus `N`, but we only call this function on Paillier encryption keys. Once all the ZKPs have encryption keys typed everywhere (instead of plain `BigNumber`s), we could change this function signature to take `n: PaillierEncryptionKey`. It would fit our use case but isn't required for the general definition.

### CODE REVIEW

File: src/utils.rs [hunk 1]
```diff
@@ -151,15 +150,27 @@ pub(crate) fn positive_bn_random_from_transcript(
...
-        }
-    }
-    BigNumber::zero()
+/// Generate a random `BigNumber` that is in the multiplicative group of integers modulo `n`.
+///
+/// This method draws a random element in the range `[0, n-1]`, then checks that it is
+/// non-zero and coprime with `n`.
+/// Coprimality is tested by checking that the least common multiple is equal to the product of
+/// `n` and the element.
+///
```
Comment (marsella) [inline src/utils.rs:159]: I added this because I wanted to be explicit about how we're checking group membership, but actually it might be dumb to have 4 lines of documentation explaining what a 4-line function does.

File: src/utils.rs [hunk 2]
```diff
@@ -151,15 +150,27 @@ pub(crate) fn positive_bn_random_from_transcript(
...
+/// Note: In this application, `n` is typically the product of two primes. If the drawn element
+/// is coprime with `n`, then the caller has accidentally stumbled upon the factorization of `n`!
+/// This is a security issue when `n` is someone else's Paillier modulus, but it is highly
```
Comment (indomitableSwan) [inline src/utils.rs:162]: This doesn't quite say what you mean it to say.
- If the drawn element is _not_ coprime with `n` and the element is not `0 mod n`, then you have accidentally stumbled upon the factorization, the chance of which is basically 0.

File: src/utils.rs (hunk 1 above)
Comment (indomitableSwan) [reply src/utils.rs:159]: Why not just check the gcd?

**Review by indomitableSwan — CHANGES_REQUESTED** [review]
I realized I effectively reviewed this PR with my previous comments.

File: src/utils.rs (hunk 1 above)
Comment (marsella) [reply src/utils.rs:159]: You know, I actually started with a gcd check and then second-guessed myself repeatedly to end up here. I will switch back.

Comment (indomitableSwan) [reply src/utils.rs]: My guess is that if you look at how lcm is implemented, it calculates the gcd.

**Review by indomitableSwan — APPROVED** [review]
LGTM.
