### PR TITLE
More comprehensive tests for `PiPrmProof`

### LINKED ISSUE #111: Write tests for PiPrmProof
A `PiPrmProof` is a statistically-secure proof with a set of challenges that the prover can guess correctly 50% of the time. Some ideas for tests:

- Choose bad secret input `lambda`
- Send a proof with too few and too many elements
- Swap one or more of the challenges (`e_i`) for incorrect values (e.g. not derived from the transcript).
- Swap one or more commitments (`A_i`) for incorrect values
- Swap one or more responses (`z_i`) for incorrect values
- Verify the proof with different common input (`N, s, t`) than was used to create it

Related issue: #51

### PR DESCRIPTION
**Pull request by amaloz**
Closes #111.

Adds a bunch of tests for `PiPrmProof`:

* Choose bad secret input lambda
* Send a proof with too few and too many elements
* Swap one or more of the challenges (e_i) for incorrect values (e.g. not derived from the transcript).
* Swap one or more commitments (A_i) for incorrect values
* Swap one or more responses (z_i) for incorrect values
* Verify the proof with different common input (N, s, t) than was used to create it

### CODE REVIEW

**Comment by marsella** [comment]
I changed the base to see the diff more clearly. When #150 gets merged, it'll automatically switch back to main.

File: src/ring_pedersen.rs [hunk 1]
```diff
@@ -126,18 +126,8 @@ impl VerifiedRingPedersen {
...
-        let t = tau.modpow(&BigNumber::from(2), modulus);
-        let s = t.modpow(&lambda, modulus);
-        let scheme = RingPedersen {
-            modulus: modulus.clone(),
-            s,
-            t,
-        };
-        let secrets = PiPrmSecret::new(lambda, totient.clone());
+        let (scheme, lambda, totient) = RingPedersen::extract(sk, rng)?;
+        let secrets = PiPrmSecret::new(lambda, totient);
```
Comment (marsella) [inline src/ring_pedersen.rs:130]: Nice de-duplication.

File: src/zkp/piprm.rs [hunk 2]
```diff
@@ -156,42 +156,129 @@ impl Proof for PiPrmProof {
...
+        let mut rng = crate::utils::get_test_rng();
+        let (input, proof, _, _) = random_ring_pedersen_proof(&mut rng)?;
+        let serialized = bincode::serialize(&proof).unwrap();
+        let deserialized: PiPrmProof = bincode::deserialize(&serialized).unwrap();
+        assert_eq!(serialized, bincode::serialize(&deserialized).unwrap());
+        deserialized.verify(&input)
+    }
+
+    #[test]
+    fn incorrect_lengths_fails() -> Result<()> {
```
Comment (marsella) [inline src/zkp/piprm.rs:191]: suggestion: This only tests the too-short case. Can we also check too-long?

File: src/zkp/piprm.rs [hunk 3]
```diff
@@ -156,42 +156,129 @@ impl Proof for PiPrmProof {
...
+    #[test]
+    fn bad_secret_exponent_fails() -> Result<()> {
+        let mut rng = crate::utils::get_test_rng();
+        let (input, _, _, totient) = random_ring_pedersen_proof(&mut rng)?;
+        {
+            let bad_lambda = random_positive_bn(&mut rng, &totient);
+            let secrets = PiPrmSecret::new(bad_lambda, totient);
+            let proof = PiPrmProof::prove(&mut rng, &input, &secrets)?;
+            assert!(proof.verify(&input).is_err());
+        }
```
Comment (marsella) [inline src/zkp/piprm.rs:233]: question: Why is this in `{}`?

**Review by marsella — COMMENTED** [review]
I just have a few questions. I prefer your method of changing a single item in the proof to the one I used in `PiEnc` (saving the original value and putting it back).

File: src/zkp/piprm.rs (hunk 3 above)
Comment (amaloz) [reply src/zkp/piprm.rs]: No reason :-). Fixed!

File: src/zkp/piprm.rs (hunk 2 above)
Comment (amaloz) [reply src/zkp/piprm.rs:191]: Done!
