### PR TITLE
"Closes #256":  Bad message routing tests

### LINKED ISSUE #256: Add bad-message-routing tests to participant
#235 adds some additional conditions on the messages processed by a `Participant` in `process_single_message`. Add negative tests to make sure these things are properly rejected:

- [x] messages with the wrong session ID get rejected
- [x] messages with the wrong participant `to` field get rejected
- [x] messages with a `from` field that's not in the participant set get rejected
- [x] messages with the right session ID but wrong protocol type get rejected

For the `from` field check, we currently _don't_ have a check that this field is in the set of valid participants, so you'll have to add it. The set of valid participants is held by the `ProtocolParticipant`. You'll have to move the `all_participants` method from the `InnerProtocolParticipant` trait to `ProtocolParticipant` so it can be accessed in `process_single_message()`. For context: together, these two traits define the set of operations that a protocol participant must implement; the `ProtocolParticipant` only holds the "public-facing" methods that are called in the `Participant` public methods (`new()` and `process_single_message()`). It's fine to move stuff between the two traits; we want to maintain the minimum number of methods in `ProtocolParticipant`, though.

- [x] Move `all_participants` method to `ProtocolParticipant`
- [x] Add check in `process_single_message()` that the message `from` field is in the set returned by `participant.all_participants()`.

### PR DESCRIPTION
**Pull request by hridambasu**
Moved all_participants method to ProtocolParticipant
Wrote 4 negative tests for process_single_message()

### CODE REVIEW

**Review by marsella — COMMENTED** [review]
I think the weird errors you're getting are because the `id` and `other_ids` methods are duplicated in `ProtocolParticipant` and `InnerProtocolParticipant`. You can just delete one of them, rather than disambiguating between identical functions. Those two traits are not independent; we realistically want every type that instantiates one to instantiate both. They're separate because `PP` is the functions that technically have to be public in order for our generalized `Participant` type to work. However there are a bunch of protocol-participant-related methods that are not important to the calling application (and would probably be confusing if they could see them), and these are all contained (and hidden from external users) in `InnerProtocolParticipant`. In this case, the ID methods are not private at all because the calling application is the one who chose the IDs in the first place. So it's fine to move them to `PP`, remove them from `IPP`, and be done with it.

File: src/protocol.rs [hunk 1]
```diff
@@ -407,6 +416,132 @@ mod tests {
     use std::collections::HashMap;
     use tracing::debug;
 
+    //#[cfg_attr(feature = "flame_it", flame)]
```
Comment (marsella) [inline src/protocol.rs:419]: nit: remove commented code. This line is used for generating the flamegraph for benchmarking. We don't need it on any tests other than the one that runs the whole protocol.

File: src/protocol.rs [hunk 2]
```diff
@@ -407,6 +416,132 @@ mod tests {
...
+    #[test]
+    fn process_single_message_wrong_session_id() -> Result<()> {
```
Comment (marsella) [inline src/protocol.rs:421]: todo: For test naming, I like to have the name be almost a sentence describing what property is being tested. This makes it way easier when you run the tests to understand what is actually failing (because `cargo test` just prints out the long list of test names with no further context). In this case, I might do something like
```rust
fn participant_rejects_messages_with_wrong_session_id()
```
or maybe
```rust
fn process_single_message_rejects_mismatched_session_id()
```

File: src/protocol.rs [hunk 3]
```diff
@@ -407,6 +416,132 @@ mod tests {
...
+        let unverified_bytes = vec![0x01, 0x02, 0x03];
+        let message = Message::new(message_type, identifier, from, to, &unverified_bytes);
+        let participant = auxinfo_quorum.iter_mut().choose(&mut rng).unwrap();
+
+        if let Err(e) = participant.process_single_message(&message, &mut rng) {
+            assert_eq!(
+                e,
+                InternalError::CallingApplicationMistake(CallerError::WrongSessionId)
+            );
+        };
```
Comment (marsella) [inline src/protocol.rs:448]: todo: this test will actually pass if `process_single_message` doesn't throw an error, since it'll skip this condition entirely and hit `Ok(())`. Consider breaking this into two asserts (is it an error? is it the right error?) like:
```rust
let result = participant.process_single_message(...);
assert!(result.is_err());
assert_eq!(result.unwrap_err(), InternalError::CallingApplicationMistake(CallerError::WrongSessionId));

File: src/protocol.rs [hunk 4]
```diff
@@ -407,6 +416,132 @@ mod tests {
...
+        let auxinfo_sid = Identifier::random(&mut rng);
+        let auxinfo_sid1 = Identifier::random(&mut rng1);
+        let mut auxinfo_quorum = configs
+            .iter()
+            .map(|config| Participant::<AuxInfoParticipant>::from_config(config, auxinfo_sid, ()))
+            .collect::<Vec<_>>();
+        let auxinfo_quorum1 = configs
+            .iter()
+            .map(|config| Participant::<AuxInfoParticipant>::from_config(config, auxinfo_sid1, ()))
+            .collect::<Vec<_>>();
```
Comment (marsella) [inline src/protocol.rs:528]: todo: Instead of generating a whole quorum here, you can create a single random participant ID, like
```rust
let bad_sender_pid = ParticipantIdentifier::random(&mut rng);
```

File: src/protocol.rs [hunk 5]
```diff
@@ -407,6 +416,132 @@ mod tests {
...
+            .map(|config| Participant::<AuxInfoParticipant>::from_config(config, auxinfo_sid, ()))
+            .collect::<Vec<_>>();
+
+        let message_type = MessageType::Auxinfo(crate::messages::AuxinfoMessageType::Public);
+        let from = auxinfo_quorum[0].id;
+        let to = auxinfo_quorum[0].id;
+        let unverified_bytes = vec![0x01, 0x02, 0x03];
+        let message = Message::new(message_type, auxinfo_sid, from, to, &unverified_bytes);
+        let participant = auxinfo_quorum.iter_mut().choose(&mut rng).unwrap();
+        if let Err(e) = participant.process_single_message(&message, &mut rng) {
```
Comment (marsella) [inline src/protocol.rs:472]: todo: This test shouldn't pass consistently. We choose a random participant from the quorum here and set the `to` field to also be a valid participant ID from the quorum, so I'd expect this to pass about a third of the time. I would recommend intentionally choosing a (participant, ID) pair that don't match, so that this will always fail as expected.

I think this passes because of the comment above -- if `process_single_message` returns `Ok(...)`, we skip the assert and the test passes.

File: src/protocol.rs [hunk 6]
```diff
@@ -155,6 +155,15 @@ impl<P: ProtocolParticipant> Participant<P> {
             }
         };
 
+        // Check messages with a from field belongs to the list of participants
```
Comment (marsella) [inline src/protocol.rs:158]: nit: all messages have a from field! You can state this more confidently, like
```
// Check that message is from a participant in this session
```

**Review by marsella — CHANGES_REQUESTED** [review]
Thanks for your work on this! I left a comment earlier about reducing the weirdness in specifying which trait's `id()` function is being called. Here's another pass of initial feedback.

I left a few comments about the structure of the first test with recommendations for utility functions. Those comments apply to all of the tests, though, so please apply them across the board.

**Comment by hridambasu** [comment]
incorporated all changes. works now. please let me know if I missed something.

File: src/auxinfo/participant.rs [hunk 7]
```diff
@@ -527,7 +527,12 @@ impl AuxInfoParticipant {
 
         Ok((
             decryption_key.into(),
-            AuxInfoPublic::new(self.retrieve_context(), self.id(), encryption_key, params)?,
+            AuxInfoPublic::new(
+                self.retrieve_context(),
+                <AuxInfoParticipant as ProtocolParticipant>::id(self),
```
Comment (marsella) [inline src/auxinfo/participant.rs:532]: todo: Now that there's only one `id` function, you can replace this with just `self.id()` -- you don't have to specify which trait it belongs to any more.

File: src/auxinfo/participant.rs [hunk 8]
```diff
@@ -723,7 +728,11 @@ mod tests {
         }
 
         // Check that private outputs are consistent
-        for ((publics, private), pid) in outputs.iter().zip(quorum.iter().map(|p| p.id())) {
+        for ((publics, private), pid) in outputs.iter().zip(
+            quorum
+                .iter()
+                .map(<AuxInfoParticipant as ProtocolParticipant>::id),
```
Comment (marsella) [inline src/auxinfo/participant.rs:734]: todo: replace with a closure (`| p | p.id()`) or non-trait-specified function (`AuxinfoParticipant::id`)

File: src/errors.rs [hunk 9]
```diff
@@ -72,11 +72,11 @@ pub enum InternalError {
...
 #[allow(missing_docs)]
 pub enum CallerError {
-    #[error("Recieved a message with the wrong recipient ID")]
+    #[error("Received a message with the wrong recipient ID")]
     WrongMessageRecipient,
-    #[error("Recieved a message with the wrong session ID")]
+    #[error("Received a message with the wrong session ID")]
     WrongSessionId,
-    #[error("Recieved a message with the wrong protocol type for this participant (malicious behavior suspected)")]
+    #[error("Received a message with the wrong protocol type for this participant (malicious behavior suspected)")]
```
Comment (marsella) [inline src/errors.rs:79]: Thank you!! You may be the only person on this project who can spell this word consistently :facepalm:

File: src/keygen/participant.rs [hunk 10]
```diff
@@ -225,7 +225,8 @@ impl KeygenParticipant {
     ) -> Result<Vec<Message>> {
         info!("Generating round one keygen messages.");
 
-        let (keyshare_private, keyshare_public) = new_keyshare(self.id(), rng)?;
+        let (keyshare_private, keyshare_public) =
+            new_keyshare(<KeygenParticipant as ProtocolParticipant>::id(self), rng)?;
```
Comment (marsella) [inline src/keygen/participant.rs:229]: todo: replace with `self.id()`

File: src/participant.rs [hunk 11]
```diff
@@ -243,15 +247,14 @@ pub(crate) trait InnerProtocolParticipant: ProtocolParticipant {
     ) -> Result<(ProcessOutcome<Self::Output>, bool)> {
         self.local_storage_mut().store::<T>(message.from(), ());
         // If message came from self, then tell the other participants that we are ready
-        let self_initiated_outcome = if message.from() == self.id() {
-            let messages = self
-                .other_ids()
+        let self_initiated_outcome = if message.from() == ProtocolParticipant::id(self) {
```
Comment (marsella) [inline src/participant.rs:250]: todo: replace `ProtocolParticipant::id(self)` with `self.id()`

File: src/participant.rs [hunk 12]
```diff
@@ -243,15 +247,14 @@ pub(crate) trait InnerProtocolParticipant: ProtocolParticipant {
...
+            let messages = ProtocolParticipant::other_ids(self)
```
Comment (marsella) [inline src/participant.rs:251]: todo: replace `ProtocolParticipant::other_ids(self)` with `self.other_ids()`

File: src/participant.rs [hunk 13]
```diff
@@ -243,15 +247,14 @@ pub(crate) trait InnerProtocolParticipant: ProtocolParticipant {
...
                 .iter()
                 .map(|other_id| {
                     Message::new(
                         message.message_type(),
                         message.id(),
-                        self.id(),
+                        ProtocolParticipant::id(self),
```
Comment (marsella) [inline src/participant.rs:257]: todo: replace with `self.id()`

File: src/participant.rs [hunk 14]
```diff
@@ -277,7 +280,7 @@ pub(crate) trait InnerProtocolParticipant: ProtocolParticipant {
     where
         T::Value: Default,
     {
-        let pid = self.id();
+        let pid = ProtocolParticipant::id(self);
```
Comment (marsella) [inline src/participant.rs:283]: todo: replace with `self.id()`

File: src/protocol.rs [hunk 15]
```diff
@@ -407,6 +416,127 @@ mod tests {
     use std::collections::HashMap;
     use tracing::debug;
 
+    #[cfg(test)]
```
Comment (marsella) [inline src/protocol.rs:419]: nit: this isn't necessary, you can remove it.

The whole test module is already tagged with `#[cfg(test)]`, so we don't have to flag individual tests as well. You can read [the Rust book chapter on tests](https://doc.rust-lang.org/book/ch11-00-testing.html) and especially the [section on test organization](https://doc.rust-lang.org/book/ch11-03-test-organization.html#the-tests-module-and-cfgtest) for details on the standard organization and labelling of tests.

File: src/protocol.rs [hunk 16]
```diff
@@ -407,6 +416,127 @@ mod tests {
...
+        let result = participant.process_single_message(&message, &mut rng);
+        assert!(result.is_err());
+        assert_eq!(
+            result.unwrap_err(),
+            InternalError::CallingApplicationMistake(CallerError::WrongSessionId)
+        );
+        Ok(())
+    }
+
+    #[cfg(test)]
```
Comment (marsella) [inline src/protocol.rs:451]: nit: this isn't necessary, you can remove.

**Review by marsella — CHANGES_REQUESTED** [review]
This is looking better. There are a lot of comments here but it's mainly to flag the same issue that appears multiple times across the PR.

There are still a few unresolved comments from my previous review, too. Let's check in about them offline.

File: src/keygen/participant.rs [hunk 17]
```diff
@@ -247,7 +247,7 @@ impl KeygenParticipant {
     ) -> Result<Vec<Message>> {
         info!("Generating round one keygen messages.");
 
-        let (keyshare_private, keyshare_public) = new_keyshare(self.id(), rng)?;
+        let (keyshare_private, keyshare_public) = new_keyshare(KeygenParticipant::id(self), rng)?;
```
Comment (marsella) [inline src/keygen/participant.rs:250]: nit: This can just be `self.id()`.

File: src/protocol.rs [hunk 18]
```diff
@@ -155,6 +150,20 @@ impl<P: ProtocolParticipant> Participant<P> {
...
+            Err(CallerError::WrongMessageRecipient)?
+        }
+
+        // Check that message is from a participant in this session
+        if !self
+            .participant
+            .all_participants()
+            .contains(&message.from())
+        {
+            Err(CallerError::WrongMessageRecipient)?
```
Comment (marsella) [inline src/protocol.rs:164]: todo: Let's make a separate error for this case so it's easier for the caller to understand what went wrong. You can add it to `CallerError` just like the others -- maybe like `InvalidMessageSender`.

File: src/protocol.rs [hunk 19]
```diff
@@ -285,9 +294,40 @@ impl ParticipantConfig {
...
+            .take(size)
+            .collect::<Vec<_>>();
+
+        let random_configs: Vec<ParticipantConfig> = (0..size)
+            .map(|i| {
+                let mut other_ids = ids.clone();
+                let id = other_ids.swap_remove(i);
+                Self { id, other_ids }
+            })
+            .collect();
```
Comment (marsella) [inline src/protocol.rs:309]: todo: this is a bit overkill -- it makes a whole set of configs when we really just need one! I would just generate the one additional `self` id, like
```rust
// normally we don't put asserts in code, but since this is for testing only, it's ok.
assert!(size > 1);
let other_ids = std::iter::repeat_with(|| PId::random(rng))
    .take(size - 1)
    .collect::<Vec<_>>();
let id = PId::random(rng);
Self { id, other_ids }
```

File: src/protocol.rs [hunk 20]
```diff
@@ -407,6 +474,134 @@ mod tests {
...
+        // Set up a single valid participant
+        let config = ParticipantConfig::random(QUORUM_SIZE, &mut rng);
+        let auxinfo_sid = Identifier::random(&mut rng);
+        let mut participant =
+            Participant::<AuxInfoParticipant>::from_config(&config, auxinfo_sid, ());
+
+        //message with the wrong protocol type
+        let message = participant.initialize_message();
+        let bad_sender_pid = ParticipantIdentifier::random(&mut rng);
+        assert_ne!(participant.id(), bad_sender_pid);
```
Comment (marsella) [inline src/protocol.rs:587]: nit: this isn't quite the right check. We want to make sure that the `bad_sender_pid` isn't in the list of possible senders, which is `participant.all_participants()`. You can check if that list [contains](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.contains) the bad pid.

**Review by marsella — COMMENTED** [review]
This looks way better! Thanks for addressing the comments. I have a few other small nits, but nothing major.

It does look like something went funky in the commit history. I'm not sure how that happened but I tried squashing locally on my machine and the diff is as expected, so I think it'll be ok as long as you squash and merge via GitHub.

Reminders
- Please update the PR description with a github closing keyword so this gets linked to the issue you solve (like "Closes #256").

**Review by marsella — COMMENTED** [review]
Since other stuff is getting committed to main, here are some instructions for cleaning up the git history.

1. Simplify the history on this branch. This will turn the 47 commits you have now into one, with the commit message as specified. The commit hash in the reset command is the last commit that is synced with main.
```bash
$ git reset --soft  f4b0e63 && git commit -m "add tests for badly-routed messages #256"
```
2. Rebase onto main.
```bash
$ git checkout main
$ git pull
$ git checkout bad-msg-routing-tests
$ git rebase main
```
It'll tell you there are merge conflicts. Resolve these in your editor -- I think the correct behavior is to accept neither change (you moved the `id` and `other ids` functions to a different trait, and Rawane moved the `retrieve_context` function up a few lines). Then make sure ci still runs and continue the rebase
```bash
$ cargo +nightly fmt
$ cargo make ci
... should pass ...
$ git add .
$ git rebase --continue
...
[detached HEAD 3449916] add tests for badly-routed messages #256
 8 files changed, 211 insertions(+), 55 deletions(-)
Successfully rebased and updated refs/heads/bad-msg-routing-tests.
```
3. Push your changes to github. The log will now show you up-to-date with `origin/main`, since the rebase worked:
```sh
$ git log
commit 34499167942f3969edf96e49602882358c6b5c1d (HEAD -> bad-msg-routing-tests)
Author: Hridam Basu <your_email@whatever.com>
Date:   Thu Apr 20 11:12:58 2023 -0400

    add tests for badly-routed messages #256

commit e73daf66099c2b13d00a03e310bb1ccb9f63be90 (origin/main, origin/HEAD, main)
Merge: f4b0e63 1ee86af
Author: Rawane Issa <rawaneissa@gmail.com>
Date:   Thu Apr 20 10:54:28 2023 -0400

    Merge pull request #280 from boltlabs-inc/239-idcontext
    
    Adds the participant ids to the participant context in presign, keygen, brodcast and auxinfo.
...
```
This is the state we want to achieve! So you can force-push your changes to this branch.
```bash
$ git push --force
```

Force-push means you'll delete the commits that are currently on this branch and replace them with your new one. In this setting, that's fine, because you own this branch and other people aren't working on it simultaneously. You should not force push to main (we've actually disallowed it on github) because that would change the commit history for everyone and would make a mess.

After these steps, the CI will run again. You can repeat steps 2 and 3 each time you need to update your branch to main. When there's more than one commit on your branch, step 2 will loop on the second set of tasks each time one of the commits conflicts with main; you just keep fixing stuff and `--continue`ing until it says you're done.

**Review by marsella — APPROVED** [review]
Please update the PR description with a closing keyword before you merge.

Otherwise, looks good to me!
