### PR TITLE
Fixes missing context from pisch. Removes verify_with_transcript. Mak…

### LINKED ISSUE #299: Pass context to pisch precommitment proofs
When we addressed #237 or #238, we missed one case where a ZK proof needs to take context as a parameter instead of instantiating it itself. This is in `pisch`, which has an interface that doesn't quite match the standard `Proof` template. Because of the way it's used in the proof, it's broken into three phases: precommit, prove, and verify.

In fact, the `verify` method on the `PiSchProof` is never used right now, despite correctly using a transcript and context! There's a `verify_with_transcript` method instead that should have been replaced in an earlier refactor.

- [ ] Update `PiSchProof::prove_from_precommit` function to take context as a parameter
- [ ] Get rid of the `verify_with_transcript` method, since it should do exactly the same thing now that `verify` also takes a transcript. Make sure the final function takes context as a parameter
- [ ] Mark the implementation of the `ProofContext` trait for `()` as test-only

### PR DESCRIPTION
**Pull request by Ra1issa**
Fixes #299: Add missing context to the PiSch proof and remove unecessary verify_with_transcript method.

### CODE REVIEW

File: src/keygen/participant.rs [hunk 1]
```diff
@@ -747,6 +751,9 @@ mod tests {
             let inbox = inboxes.get_mut(&participant.id).unwrap();
             inbox.push(participant.initialize_keygen_message(keyshare_identifier));
         }
+        let mut participant_ids = quorum[0].all_participants();
+        participant_ids.sort();
```
Comment (marsella) [inline src/keygen/participant.rs:755]: question: does this need to be used somewhere?

File: src/zkp/mod.rs [hunk 2]
```diff
@@ -33,6 +33,7 @@ pub(crate) trait ProofContext {
     fn as_bytes(&self) -> Vec<u8>;
 }
 
+#[cfg(test)]
 /// This is a temporary preliminary implementation that will be modified by
 /// issue #240.
```
Comment (marsella) [inline src/zkp/mod.rs:38]: nit: This is now outdated! Maybe change this to a line recommending against use in an actual protocol in case someone is tempted to remove the `#[cfg(test)]` later? Or just remove.

**Review by marsella — APPROVED** [review]
This looks great, thank you! One tiny nit and a question but you can merge once they're addressed.

File: src/keygen/participant.rs (hunk 1 above)
Comment (Ra1issa) [reply src/keygen/participant.rs:755]: nop. good catch.
