### PR TITLE
extract_message function on Broadcast Output

### LINKED ISSUE #291: Add `BroadcastOutput::extract_message` method
We see the following code pattern crop up in the various protocol implementations:
```rust
        if broadcast_message.tag != BroadcastTag::KeyGenR1CommitHash {
            return Err(InternalError::IncorrectBroadcastMessageTag);
        }
        let message = &broadcast_message.msg;
```
It'd be better to encapsulate this into a method on `BroadcastOutput` such as:
```rust
pub(crate) fn extract_message(&self, expected_tag: BroadcastTag) -> Result<&Message>
```

# Tasks
- [x] Implement `extract_message` method
- [x] Make the `msg` and `tag` fields on `BroadcastOutput` private, if possible
- [x] Replace existing hand-rolled code with new method

### PR DESCRIPTION
**Pull request by hridambasu**
Closes #291

### CODE REVIEW

File: src/errors.rs [hunk 1]
```diff
@@ -27,6 +27,8 @@ pub enum InternalError {
     InternalInvariantFailed,
     #[error("Storage does not contain the requested item")]
     StorageItemNotFound,
+    #[error("Broadcast Message does not have the correct tag")]
+    IncorrectBroadcastMessageTag,
```
Comment (marsella) [inline src/errors.rs:31]: todo: We're trying to consolidate errors into a smaller set that defines what action the calling application should take, so I recommend removing this and using the `ProtocolError` variant instead -- that's an indication that a different participant tagged the message incorrectly and it's not a problem the calling application has to deal with.

I think the issue was written before #268 removed this error type; you can see more discussion on the goals of the `InternalError` type in the comments of #157.

File: src/broadcast/participant.rs [hunk 2]
```diff
@@ -83,8 +83,22 @@ pub(crate) struct BroadcastIndex {
...
 #[derive(Debug, Clone, Serialize, Deserialize)]
 pub(crate) struct BroadcastOutput {
-    pub(crate) tag: BroadcastTag,
-    pub(crate) msg: Message,
+    tag: BroadcastTag,
+    msg: Message,
+}
+
+impl BroadcastOutput {
+    pub(crate) fn extract_message(&self, expected_tag: BroadcastTag) -> Result<&Message> {
```
Comment (marsella) [inline src/broadcast/participant.rs:91]: suggestion: can this take self by value instead of by reference? I think in most cases extracting the message is the last step of processing a broadcast output so we can consume the memory.

**Review by marsella — CHANGES_REQUESTED** [review]
Nice, this really makes the message handling so much easier to parse.

File: src/broadcast/participant.rs (hunk 2 above)
Comment (marsella) [reply src/broadcast/participant.rs:91]: If this works, you can rename the function to `into_message`, following [Rust's naming conventions for conversion functions](https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv).

File: src/auxinfo/participant.rs [hunk 3]
```diff
@@ -331,10 +331,12 @@ impl AuxInfoParticipant {
     ) -> Result<ProcessOutcome<<Self as ProtocolParticipant>::Output>> {
         info!("Handling round one auxinfo message.");
 
-        let message = broadcast_message.extract_message(BroadcastTag::AuxinfoR1CommitHash)?;
+        let message = broadcast_message
+            .clone()
```
Comment (marsella) [inline src/auxinfo/participant.rs:335]: Oh, hm. The goal of taking this by value is to avoid cloning or, more generally, copies of the type floating around longer than we need them. It's not security critical in this case but that is the design motivation. Here I guess we'd have to go up and see if we can pass the `BroadcastOutput` by value to the `handle_round_one_msg` method.

I think that will go bother the slightly complicated `convert` method as well, but I think it should compile. Happy to walk through the fancy types in that function next week, if you'd like.

Comment (hridambasu) [reply src/auxinfo/participant.rs:335]: I see. Sure we can go through it together either today or tomorrow if you are free

**Review by marsella — APPROVED** [review]
Looks good to me, thanks!
