### PR TITLE
113 pifac tests

### LINKED ISSUE #113: Write tests for PiFacProof
A `PiFacProof` has nine elements that must satisfy five different constraints. Some ideas for tests:
- Swap each of the proof elements for a different, random element (of the correct type). Proof shouldn't verify.
- Bad inputs: try with small p, large q, and vice-versa. The range checks should fail.
- Try verifying the proof with different setup or public parameters than were used to construct it.

Related issue: #47.

### PR DESCRIPTION
**Pull request by hridambasu**
Closes #113

### CODE REVIEW

File: src/zkp/pifac.rs [hunk 1]
```diff
@@ -491,6 +495,84 @@ mod tests {
         Ok(())
     }
 
+    #[test]
+    fn proof_elements_should_be_correct() -> Result<()> {
```
Comment (marsella) [inline src/zkp/pifac.rs:499]: todo: This test is a good place to use the `with_random_no_small_factors_proof` approach, since we're starting with a valid input + proof, then modifying the proof one field at at time. That means you would skip the lines defining the input and proof and put everything else in your closure.

nit: please consider breaking up the block of code with some comments or newlines. Maybe separating each type of substitution (e.g. "replace each `BigNumber`; replace each `Commitment`..._) would be a reasonable separation. I just get lost in so many unbroken lines of code.

**Review by marsella — CHANGES_REQUESTED** [review]
Some minor nits on this test.

You noted that some tests already exist but they are actually not complete as is. There's some discussion and checklists in the comments of #113. Please add the missing pieces noted there, and double check whether anything else is also missing.

File: src/zkp/pifac.rs (hunk 1 above)
Comment (hridambasu) [reply src/zkp/pifac.rs:529]: If one field is already wrong, then isn't it redundant to put cumulatively n fields wrong in the nth assert? rather than testing whether each field is wrong separately does not work?

File: src/zkp/pifac.rs [hunk 2]
```diff
@@ -467,23 +482,37 @@ mod tests {
         with_random_no_small_factors_proof(&mut rng, correct_factors)
     }
 
-    /// TODO: This test does not currently work. It should be addressed as part
-    /// of issue #113.
-    // #[test]
-    #[allow(dead_code)]
-    fn test_modulus_cannot_have_small_factors() -> Result<()> {
+    #[test]
+    fn test_modulus_cannot_have_large_factors() -> Result<()> {
```
Comment (marsella) [inline src/zkp/pifac.rs:486]: suggestion (style preference): I think this would be clearer if we distinguished less between `p` and `q` in the variable naming. The idea is that we have a big factor (product of two large primes) and a small factor (2) and the modulus is a product of those two things. We don't have to separately rename them depending in which one we pass first in the secret.

If I were writing this, I would make a `small_factor` and `big_factor`, multiply them to get the `modulus`, and then reuse those three fields for both proofs, rather than cloning and re-calculating stuff.

**Review by marsella — COMMENTED** [review]
Thanks for adding some additional tests. There are still a few things missing that are noted in the comments on the original issue:
- [x] The `test_no_small_factors_proof_negative_cases` needs to be broken into smaller tests. The monolithic thing is hard to read and hard to know what's being tested and there's no reason for it to be one giant test full of independent assertions.
- [ ] Many of the pre-existing tests are not testing what they claim to be testing. Many assertions are failing because the test is being proved and verified with different common inputs, but the comments suggest that the tests are validating properties on the secret inputs. These need to be fixed or removed.

**Comment by hridambasu** [comment]
@marsella Fixed all your comments. Didn't notice any check related to common input in stead of secret input. If you do notice, please let me know and I'll fix them.

**Review by marsella — COMMENTED** [review]
> Didn't notice any check related to common input in stead of secret input. If you do notice, please let me know and I'll fix them.

I made a separate issue #465 to address my remaining concern.

In a call a while ago, we talked about documenting `test_modulus_cannot_have_large_factors` to explain how the range check in the proof looks for "too large", not "too small", despite the name of the proof. This needs to be captured somewhere before this can be merged.

Otherwise looks good.

**Comment by marsella** [comment]
@hridambasu Please write documentation about the range check in the proof either in the original testing issue (to close the loop) or in the documentation for the proof in the code. Then I will approve.

**Comment by hridambasu** [comment]
@marsella  I documented this in the original issue.

**Review by marsella — APPROVED** [review]
