### PR TITLE
remove non-failure error from pimod

### LINKED ISSUE #419: Distinguish Error PiMod
We're talking about the PiMod ZKP; this is a code quality issue, not a correctness issue.
In arithmetic functions, determine when a failure is an actual customer-facing error vs an expected internal error, and try to refactor to use Options in the latter case. See [comment](https://github.com/boltlabs-inc/tss-ecdsa/pull/235#discussion_r1142645045). 
The problem is that we raise our external-facing errors in cases where it's actually not an external facing error (it's an internal thing that's expected to not work a bunch of times before it does work)
A better solution would be to only raise an InternalError when we actually have a problem, and use a different paradigm to indicate "it didn't work this time but we haven't given up yet."

### PR DESCRIPTION
**Pull request by marsella**
Closes #419

There are more issues to fix here, I think, in terms of code quality, but this should fix the specific "spam the error logs" problem we've seen. Before I close this I will write another issue with some more specifics.

### CODE REVIEW

File: src/zkp/pimod.rs [hunk 1]
```diff
@@ -371,40 +371,51 @@ fn square_roots_mod_composite(
...
-    let (z1, z2) = square_roots_mod_prime(n, q)?;
+) -> Result<Option<[BigNumber; 4]>> {
+    let (y1, y2) = match square_roots_mod_prime(n, p) {
+        Some(roots) => roots,
+        None => return Ok(None),
+    };
+    let (z1, z2) = match square_roots_mod_prime(n, q) {
+        Some(roots) => roots,
+        None => return Ok(None),
+    };
```
Comment (marsella) [inline src/zkp/pimod.rs:382]: It's not that bad, in hindsight, but these failure cases are kind of awkward, especially because I don't think we can take advantage of any nice conversion methods on `Option`s to do this kind of error handling.

File: src/zkp/pimod.rs [hunk 2]
```diff
@@ -371,40 +371,51 @@ fn square_roots_mod_composite(
...
                 for y in res {
                     fourth_roots.push(y);
                 }
             }
-            Err(_) => {
+            None => {
                 continue;
             }
         }
     }
```
Comment (marsella) [inline src/zkp/pimod.rs:417]: One potential improvement for the future is to make this return type more explicit. There are always either exactly 4 or exactly 0 4th roots returned from this method, so a more specific return type would be `Result<Option<[BigNumber; 4]>>`

**Review by hridambasu — APPROVED** [review]
Looks good to me!
